# Database (Dev - H2)
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=false
# spring.jpa.open-in-view=false

# Database (Prod - MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/underwriting_enhance?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/underwriting_enhance
# spring.data.mongodb.auto-index-creation=true

# External Systems Health Endpoints
systems.ccr.url=http://localhost:8081/health
systems.payment-gateway.url=http://localhost:8082/health
systems.bow.url=http://localhost:8083/health
systems.la.url=http://localhost:8084/health
systems.cube.url=http://localhost:8085/health
systems.casepedia.url=http://localhost:8086/health
systems.nano.url=http://localhost:8087/health
systems.int.url=http://localhost:8089/health
systems.owb-opus.url=http://localhost:8090/health
systems.uwme.url=http://localhost:8091/health
systems.fcrm.url=http://localhost:8092/health
systems.dms.url=http://localhost:8093/health

# JT400 Configuration
systems.jt400.host=192.168.1.100
systems.jt400.username=testuser
systems.jt400.password=testpass

# Http Client Configuration
http.client.connection-timeout=5000
http.client.read-timeout=5000


# Application
server.port=8080

# Legacy System Config (Mock or Real)
jt400.host=192.168.1.100
jt400.user=testuser
jt400.pass=testpass
